mode: development
media_root: media
media_url: /media
base_url: /

plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.meta.AutoExtendPlugin
    - hyde.ext.plugins.meta.SorterPlugin
    - hyde.ext.plugins.meta.TaggerPlugin
    - hyde.ext.plugins.text.TextlinksPlugin
    - hyde.ext.plugins.text.SyntextPlugin
    - hyde.ext.plugins.languages.LanguagePlugin
    - hyde.ext.plugins.urls.UrlCleanerPlugin

context:
    data:
        tweet_via: guillaumededrie
        base: http://guillaume.dedrie.fr
        languages:
            fr: Français
            en: English

meta:
    nodemeta: meta.yaml
    created: !!timestamp 2013-06-10 00:00:00
    author: Guillaume Dedrie
    charset: utf-8
    usedisqus: false

urlcleaner:
  index_file_names:
    - index.html
  strip_extensions:
    - html
  append_slash: true

sorter:
  time:
    attr: meta.created
    filters:
      source_file.kind: html
      is_processable: true
      meta.is_article: true

tagger:
  sorter: time
  archives:
    frblog:
      source: fr/blog/
      target: fr/blog/tag
      template: blog_tag.j2
      archive_extension: html
    enblog:
      source: en/blog/
      target: en/blog/tag
      template: blog_tag.j2
      archive_extension: html

