language: fr
menu:
  -
     name: "Accueil"
     page: "index.html"
  -
     name: "Blog"
     page: "blog/"
  -
     name: "Mon CV"
     page: "mon-cv.html"
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "À propos"
     page: "a-propos.html"
l10n:
  read_more: "lire plus"
  search: "Rechercher"
  follow_me: "Me suivre"
  about_this_site: "À propos de ce site"
  licence: <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.fr"><img alt="Licence Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by/3.0/88x31.png" /></a><br />Ce(tte) œuvre est mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.fr">Licence Creative Commons Attribution 3.0 non transposé</a>.
  powered_using: "Généré en utilisant"
  source_available: "Sources disponibles sur"
